# Source from repository launchers. All paths may be overridden before invocation.
FLOWBUDGET_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
export FLOWBUDGET_ROOT
FLOWBUDGET_IMAGENET="${FLOWBUDGET_IMAGENET:-${FLOWBUDGET_ROOT}/data/imagenet/train}"
FLOWBUDGET_CIFAR10="${FLOWBUDGET_CIFAR10:-${FLOWBUDGET_ROOT}/rectified_flow_cifar10/data}"
export FLOWBUDGET_IMAGENET FLOWBUDGET_CIFAR10
FLOWBUDGET_PYTHON="${FLOWBUDGET_PYTHON:-python}"
FLOWBUDGET_EVALUATOR="${FLOWBUDGET_EVALUATOR:-${FLOWBUDGET_ROOT}/../guided-diffusion/evaluations/evaluator.py}"
FLOWBUDGET_RF_CHECKPOINTS="${FLOWBUDGET_RF_CHECKPOINTS:-${FLOWBUDGET_ROOT}/rectified_flow_cifar10/checkpoints}"
FLOWBUDGET_CIFAR_REFERENCE="${FLOWBUDGET_CIFAR_REFERENCE:-${FLOWBUDGET_ROOT}/rectified_flow_cifar10/references/cifar10_test_10k.npz}"
export FLOWBUDGET_EVALUATOR FLOWBUDGET_RF_CHECKPOINTS FLOWBUDGET_CIFAR_REFERENCE
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES-${FLOWBUDGET_GPU:-0}}"
cd -- "$FLOWBUDGET_ROOT"
